version: '3.7'

volumes:
  mysql_data:

services:
  app:
    build: .
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - '../patterns:/var/www/html'

  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './configs/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '../patterns/:/var/www/html'

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=patterns
      - MYSQL_USER=patterns
      - MYSQL_PASSWORD=patternssql
      - MYSQL_ROOT_PASSWORD=patternssql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
